# Generated by Django 4.2 on 2026-02-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'biz_category',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='客户编码')),
                ('name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('tax_no', models.CharField(max_length=50, verbose_name='税号')),
                ('address', models.CharField(max_length=200, verbose_name='公司地址')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='公司邮箱')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='开户银行')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='银行账号')),
                ('bank_branch_no', models.CharField(blank=True, max_length=50, verbose_name='支行行号')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='应收余额')),
                ('remark', models.TextField(blank=True, verbose_name='备注信息')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'biz_customer',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='商品编码')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('unit', models.CharField(max_length=20, verbose_name='计量单位')),
                ('spec', models.CharField(blank=True, max_length=100, verbose_name='规格')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='条形码')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='进货价')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='销售价')),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='零售价')),
                ('min_stock', models.IntegerField(default=0, verbose_name='最低库存')),
                ('max_stock', models.IntegerField(default=0, verbose_name='最高库存')),
                ('status', models.IntegerField(choices=[(0, '下架'), (1, '上架')], default=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'biz_goods',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='供应商编码')),
                ('name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('tax_no', models.CharField(max_length=50, verbose_name='税号')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='公司邮箱')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='开户银行')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='银行账号')),
                ('bank_branch_no', models.CharField(blank=True, max_length=50, verbose_name='支行行号')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='应付余额')),
                ('remark', models.TextField(blank=True, verbose_name='备注信息')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'biz_supplier',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='仓库地址')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'biz_warehouse',
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['code'], name='biz_supplie_code_c6d0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='biz_supplie_name_beed3e_idx'),
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.category', verbose_name='商品分类'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['code'], name='biz_custome_code_be2f91_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='biz_custome_name_ab754f_idx'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='basic.category', verbose_name='父分类'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['code'], name='biz_goods_code_52cde8_idx'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['name'], name='biz_goods_name_df9b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['category'], name='biz_goods_categor_0a025a_idx'),
        ),
    ]
