# Generated by Django 4.2 on 2026-02-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-created_at'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at'], 'verbose_name': '供应商', 'verbose_name_plural': '供应商'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-created_at'], 'verbose_name': '仓库', 'verbose_name_plural': '仓库'},
        ),
    ]
