# Generated by Django 4.2 on 2026-02-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_migrate_unit_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_type',
        ),
        migrations.DeleteModel(
            name='GoodsType',
        ),
    ]
