# Generated by Django 4.2 on 2026-02-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_remove_goods_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='分类编码'),
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=1, verbose_name='层级深度'),
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, max_length=500, verbose_name='分类路径'),
        ),
        migrations.AddField(
            model_name='category',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='备注'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='biz_categor_parent__e140ed_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level'], name='biz_categor_level_1c22ed_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path'], name='biz_categor_path_2e19be_idx'),
        ),
    ]
