# Generated by Django 4.2 on 2026-02-23 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0007_add_category_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
