# Generated by Django 4.2 on 2026-02-23 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_add_unit_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='basic.unit', verbose_name='基准单位'),
        ),
        migrations.AddField(
            model_name='unit',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='换算系数'),
        ),
        migrations.AddField(
            model_name='unit',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, verbose_name='单位符号'),
        ),
    ]
