# Generated by Django 4.2 on 2026-03-12 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0009_add_unit_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='公司简称')),
                ('credit_code', models.CharField(blank=True, max_length=50, verbose_name='统一社会信用代码')),
                ('legal_person', models.CharField(blank=True, max_length=50, verbose_name='法定代表人')),
                ('registered_address', models.CharField(blank=True, max_length=300, verbose_name='注册地址')),
                ('business_address', models.CharField(blank=True, max_length=300, verbose_name='经营地址')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='传真号码')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='电子邮箱')),
                ('website', models.URLField(blank=True, verbose_name='公司网站')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='开户银行')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='银行账号')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='纳税人识别号')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='公司Logo')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='公司印章')),
                ('invoice_title', models.CharField(blank=True, max_length=200, verbose_name='发票抬头')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
                'db_table': 'sys_company_info',
            },
        ),
    ]
