# Generated by Django 4.2 on 2026-03-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_companyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='stamp',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='公司Logo数据'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='公司Logo文件名'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stamp_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='公司印章数据'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stamp_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='公司印章文件名'),
        ),
    ]
