# Generated by Django 4.2 on 2026-03-12 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0011_change_company_image_to_binary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('delivery', '送货单'), ('purchase', '采购单'), ('sale', '销售单'), ('inventory', '库存单')], default='delivery', max_length=20, verbose_name='模板类型')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认模板')),
                ('elements', models.JSONField(default=list, verbose_name='元素配置')),
                ('settings', models.JSONField(default=dict, verbose_name='打印设置')),
                ('paper_width', models.IntegerField(default=210, verbose_name='纸张宽度(mm)')),
                ('paper_height', models.IntegerField(default=140, verbose_name='纸张高度(mm)')),
                ('orientation', models.CharField(default='portrait', max_length=10, verbose_name='纸张方向')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '打印模板',
                'verbose_name_plural': '打印模板',
                'db_table': 'sys_print_template',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
