# Generated by Django 4.2 on 2026-02-18 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
        ('basic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sale_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.warehouse', verbose_name='出库仓库'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale.saleorder', verbose_name='销售单'),
        ),
    ]
