# Generated by Django 4.2 on 2026-02-18 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已入库数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '采购明细',
                'verbose_name_plural': '采购明细',
                'db_table': 'biz_purchase_item',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='采购单号')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='采购日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='总金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='已付金额')),
                ('status', models.CharField(choices=[('pending', '待入库'), ('partial', '部分入库'), ('completed', '已入库'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '采购单',
                'verbose_name_plural': '采购单',
                'db_table': 'biz_purchase_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
