# Generated by Django 4.2 on 2026-02-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.UniqueConstraint(fields=('order', 'goods'), name='unique_purchase_item_goods'),
        ),
    ]
