# Generated by Django 4.2 on 2026-02-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='库存数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'biz_inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('inbound', '入库'), ('outbound', '出库'), ('adjust', '库存调整'), ('check', '盘点')], max_length=20, verbose_name='变动类型')),
                ('change_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='变动数量')),
                ('before_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='变动前数量')),
                ('after_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='变动后数量')),
                ('related_order_type', models.CharField(blank=True, max_length=50, verbose_name='关联单据类型')),
                ('related_order_id', models.IntegerField(blank=True, null=True, verbose_name='关联单据ID')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'db_table': 'biz_inventory_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='入库单号')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='总金额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单',
                'db_table': 'biz_stock_in',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='出库单号')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='总金额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单',
                'db_table': 'biz_stock_out',
                'ordering': ['-created_at'],
            },
        ),
    ]
