# Generated by Django 4.2 on 2026-02-18 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0001_initial'),
        ('purchase', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.saleorder', verbose_name='关联销售单'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.warehouse', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchaseorder', verbose_name='关联采购单'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.warehouse', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.warehouse', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.warehouse', verbose_name='仓库'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['goods'], name='biz_invento_goods_i_178f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['warehouse'], name='biz_invento_warehou_a028b2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['created_at'], name='biz_invento_created_9cf578_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['goods'], name='biz_invento_goods_i_3a3271_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse'], name='biz_invento_warehou_b525ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('goods', 'warehouse')},
        ),
    ]
