# Generated by Django 4.2 on 2026-02-20 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0002_add_model_ordering'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='调整单号')),
                ('adjust_type', models.CharField(choices=[('increase', '库存增加'), ('decrease', '库存减少')], max_length=20, verbose_name='调整类型')),
                ('reason', models.CharField(choices=[('check', '盘点调整'), ('damage', '商品损耗'), ('return', '退货入库'), ('other', '其他原因')], max_length=20, verbose_name='调整原因')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存调整单',
                'verbose_name_plural': '库存调整单',
                'db_table': 'biz_stock_adjust',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='调拨单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_out', to='basic.warehouse', verbose_name='调出仓库')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_in', to='basic.warehouse', verbose_name='调入仓库')),
            ],
            options={
                'verbose_name': '库存调拨单',
                'verbose_name_plural': '库存调拨单',
                'db_table': 'biz_stock_transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='调拨数量')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.goods', verbose_name='商品')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer', verbose_name='调拨单')),
            ],
            options={
                'verbose_name': '库存调拨明细',
                'verbose_name_plural': '库存调拨明细',
                'db_table': 'biz_stock_transfer_item',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='调整前数量')),
                ('adjust_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='调整数量')),
                ('after_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='调整后数量')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('adjust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockadjust', verbose_name='调整单')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存调整明细',
                'verbose_name_plural': '库存调整明细',
                'db_table': 'biz_stock_adjust_item',
            },
        ),
    ]
