# Generated by Django 4.2 on 2026-02-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_update_inventory_log_remark'),
        ('inventory', '0003_add_stock_adjust_transfer'),
    ]

    operations = [
    ]
