# Generated by Django 4.2 on 2026-05-22 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_add_print_template'),
        ('inventory', '0006_alter_quantity_fields_to_int'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.goods', verbose_name='商品')),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockin', verbose_name='入库单')),
            ],
            options={
                'verbose_name': '入库单明细',
                'verbose_name_plural': '入库单明细',
                'db_table': 'biz_stock_in_item',
            },
        ),
    ]
