# Generated by Django 4.2 on 2026-02-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='姓名'),
        ),
    ]
