# Generated by Django 4.2 on 2026-02-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_set_default_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='权限列表'),
        ),
    ]
