# Generated by Django 4.2 on 2026-02-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_user_role_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.IntegerField(default=0, verbose_name='Token版本号'),
        ),
    ]
