# Generated by Django 4.2 on 2026-03-01 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='单据编号')),
                ('type', models.CharField(choices=[('pay', '付款'), ('receive', '收款')], max_length=10, verbose_name='类型')),
                ('related_order_type', models.CharField(default='', max_length=20, verbose_name='关联单据类型')),
                ('related_order_id', models.IntegerField(default=0, verbose_name='关联单据ID')),
                ('related_order_no', models.CharField(default='', max_length=30, verbose_name='关联单据编号')),
                ('related_party_type', models.CharField(default='', max_length=50, verbose_name='往来单位类型')),
                ('related_party_id', models.IntegerField(default=0, verbose_name='往来单位ID')),
                ('related_party_name', models.CharField(default='', max_length=100, verbose_name='往来单位名称')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='总金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='已付金额')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='付款方式')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='付款日期')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('partial', '部分付款'), ('paid', '已付款')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '收付款记录',
                'verbose_name_plural': '收付款记录',
                'db_table': 'biz_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='付款金额')),
                ('payment_method', models.CharField(max_length=50, verbose_name='付款方式')),
                ('payment_date', models.DateField(verbose_name='付款日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='finance.payment', verbose_name='收付款单')),
            ],
            options={
                'verbose_name': '付款记录明细',
                'verbose_name_plural': '付款记录明细',
                'db_table': 'biz_payment_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
