# Generated by Django 4.2 on 2026-02-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='单据编号')),
                ('type', models.CharField(choices=[('receive', '收款'), ('pay', '付款')], max_length=10, verbose_name='类型')),
                ('related_party_type', models.CharField(max_length=50, verbose_name='往来单位类型')),
                ('related_party_id', models.IntegerField(verbose_name='往来单位ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='付款方式')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
            ],
            options={
                'verbose_name': '收付款记录',
                'verbose_name_plural': '收付款记录',
                'db_table': 'biz_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
